# Generated by Django 4.1.7 on 2023-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
