# Generated by Django 4.1.7 on 2023-03-03 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0004_alter_useractivities_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivities',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
