# Generated by Django 4.1.7 on 2023-03-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0007_useractivities_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivities',
            name='user',
        ),
    ]
