# Generated by Django 4.1.7 on 2023-03-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0009_useractivities_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
