# Generated by Django 4.1.7 on 2023-03-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0012_alter_useractivities_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivities',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='useractivities',
            old_name='created_at1',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='useractivities',
            old_name='email1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='useractivities',
            old_name='fullname1',
            new_name='fullname',
        ),
    ]
