# Generated by Django 4.1.7 on 2023-03-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0014_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=250),
        ),
    ]
