# Generated by Django 4.1.7 on 2023-03-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0015_alter_customuser_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
    ]
