# Generated by Django 4.1.7 on 2023-03-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0016_rename_update_at_customuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivities',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
    ]
