# Generated by Django 4.1.7 on 2023-03-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0003_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventorygroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='created_by',
        ),
    ]
