# Generated by Django 4.1.7 on 2023-03-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0004_remove_inventory_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorygroup',
            name='belongs_to',
        ),
    ]
