# Generated by Django 4.1.7 on 2023-03-04 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_control', '0006_inventory_created_by_inventorygroup_belongs_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorygroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
